{
    parserClass="de.achimonline.kickassembler.acbg.parser.KickAssemblerParser"

    extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

    psiClassPrefix="KickAssembler"
    psiImplClassSuffix="Impl"
    psiPackage="de.achimonline.kickassembler.acbg.psi"
    psiImplPackage="de.achimonline.kickassembler.acbg.psi.impl"

    elementTypeHolderClass="de.achimonline.kickassembler.acbg.psi.KickAssemblerTypes"
    elementTypeClass="de.achimonline.kickassembler.acbg.psi.KickAssemblerElementType"
    tokenTypeClass="de.achimonline.kickassembler.acbg.psi.KickAssemblerTokenType"
}

kickAssemblerFile ::= root*

root ::= ( STRING |
           NUMBER |

           LEFT_PARENTHESES |
           RIGHT_PARENTHESES |
           LEFT_BRACKET |
           RIGHT_BRACKET |
           LEFT_BRACE |
           RIGHT_BRACE |

           HASH |
           ASSIGN |
           COMMA |
           SEMICOLON |
           LESS_EQUALS |
           GREATER_EQUALS |
           LESS |
           GREATER |
           BIT_AND |
           BIT_OR |
           BIT_XOR |
           BIT_NOT |
           SHIFT_LEFT |
           SHIFT_RIGHT |
           PLUS |
           MINUS |
           TIMES |
           DIVIDE |
           NOT_EQUAL |
           EQUAL |
           AND |
           OR |
           NOT |
           PLUS_PLUS |
           MINUS_MINUS |
           PLUS_EQUAL |
           MINUS_EQUAL |
           TIMES_EQUAL |
           DIVIDE_EQUAL |
           DOT |
           COLON |
           QUESTION_MARK |

           BASIC_UPSTART |
           PREPROCESSOR |
           LABEL |
           LOCAL_LABEL |
           MNEMONIC |
           COMMENT_LINE |
           COMMENT_BLOCK |

           DUMMY )
